-- 코드를 입력하세요
SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE * SALES) AS TOTAL_SALES
FROM BOOK_SALES S LEFT OUTER JOIN (SELECT A.AUTHOR_ID, AUTHOR_NAME, CATEGORY, BOOK_ID, PRICE FROM BOOK B LEFT OUTER JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID) B ON B.BOOK_ID = S.BOOK_ID
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC