SELECT MONTH, CAR_ID, RECORDS
FROM (
    SELECT 
        CAR_ID, 
        MONTH(START_DATE) AS MONTH, 
        COUNT(*) AS RECORDS, 
        SUM(COUNT(*)) OVER(PARTITION BY CAR_ID) AS C
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID, MONTH(START_DATE)
) AS T
WHERE C >= 5
ORDER BY MONTH ASC, CAR_ID DESC;
