SELECT R1.FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO R1
WHERE FAVORITES = (
    SELECT MAX(FAVORITES)
    FROM REST_INFO R2
    WHERE R1.FOOD_TYPE = R2.FOOD_TYPE
)
ORDER BY R1.FOOD_TYPE DESC