-- 코드를 작성해주세요
SELECT ID,  CASE WHEN 100 >= SIZE_OF_COLONY THEN 'LOW' WHEN 100 < SIZE_OF_COLONY AND 1000 >= SIZE_OF_COLONY THEN 'MEDIUM' WHEN 1000 < SIZE_OF_COLONY THEN 'HIGH' END AS SIZE
FROM ECOLI_DATA
ORDER BY ID ASC