-- 코드를 입력하세요
SELECT DISTINCT FOOD_PRODUCT.PRODUCT_ID, PRODUCT_NAME, SUM(PRICE * AMOUNT) AS TOTAL_SALES 
FROM FOOD_PRODUCT LEFT OUTER JOIN FOOD_ORDER ON FOOD_PRODUCT.PRODUCT_ID = FOOD_ORDER.PRODUCT_ID
WHERE FOOD_ORDER.PRODUCE_DATE LIKE '2022-05%'
GROUP BY PRODUCT_ID
ORDER BY SUM(PRICE * AMOUNT) DESC, PRODUCT_ID ASC