-- 코드를 작성해주세요
SELECT I.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO T INNER JOIN (
    SELECT B.ITEM_ID
    FROM ITEM_INFO A INNER JOIN ITEM_TREE B ON A.ITEM_ID = B.PARENT_ITEM_ID
    WHERE RARITY = 'RARE') AS I ON I.ITEM_ID = T.ITEM_ID
ORDER BY I.ITEM_ID DESC