-- 코드를 작성해주세요
SELECT YEAR, MAX - SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA A INNER JOIN (SELECT MAX(SIZE_OF_COLONY) AS MAX,YEAR(DIFFERENTIATION_DATE) AS YEAR  FROM ECOLI_DATA GROUP BY YEAR(DIFFERENTIATION_DATE)) B ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR, YEAR_DEV
