-- 코드를 작성해주세요
SELECT A.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_TREE A INNER JOIN ITEM_INFO B ON A.ITEM_ID = B.ITEM_ID
WHERE NOT EXISTS (
    SELECT ITEM_ID
    FROM ITEM_TREE B
    WHERE A.ITEM_ID = B.PARENT_ITEM_ID
)
ORDER BY ITEM_ID DESC
