-- 코드를 입력하세요
SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK INNER JOIN BOOK_SALES ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
WHERE LEFT(SALES_DATE,7) = '2022-01'
GROUP BY CATEGORY
ORDER BY CATEGORY ASC