-- 코드를 입력하세요
SELECT COALESCE(A.FLAVOR, B.FLAVOR) AS FLAVOR
FROM FIRST_HALF A JOIN (SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER FROM JULY GROUP BY FLAVOR) B ON A.FLAVOR = B.FLAVOR
ORDER BY A.TOTAL_ORDER + B.TOTAL_ORDER DESC LIMIT 3